server:
  port: 8080

spring:
  application:
    name: crypto-exchange
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/CryptoExchangeDb}
    username: ${POSTGRES_DB_USERNAME:postgres}
    password: ${POSTGRES_DB_PASSWORD:postgres}
  sql:
    init:
      platform: postgres
      mode: always
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org:
      springframework:
        security: debug
